### ISSUE TITLE
Compile ERC721A contract failed

### ISSUE THREAD

**Issue by jovijovi** [matter-labs/hardhat-zksync#82]
Compile `ERC721A` contract failed. Here is the `ERC721A` repo <https://github.com/chiru-labs/ERC721A> .

- A simple contract like this:

```solidity
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.4;

import {ERC721A} from "erc721a/contracts/ERC721A.sol";
import {ERC721AQueryable} from "erc721a/contracts/extensions/ERC721AQueryable.sol";

contract FooBarNFT is ERC721AQueryable {
    constructor(string memory name_, string memory symbol_) ERC721A(name_, symbol_) {
        //TODO:
    }
}
```

- Command:

```shell
yarn hardhat compile
```

- Error message:

```text
Solidity 0.8.12 is not fully supported yet. You can still use Hardhat, but some features, like stack traces, might not work correctly.

Learn more at https://hardhat.org/reference/solidity-support

InternalCompilerError: Invalid stack item name: slot


Error HH600: Compilation failed

For more info go to https://hardhat.org/HH600 or run Hardhat with --show-stack-traces
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

- Package deps:

```json
  "dependencies": {
    "@matterlabs/hardhat-zksync-deploy": "^0.1.5",
    "@matterlabs/hardhat-zksync-solc": "^0.3.4",
    "erc721a": "4.1.0",
    "zksync-web3": "^0.4.0"
  }
```

- hardhat.config.ts

```typescript
require("@matterlabs/hardhat-zksync-deploy");
require("@matterlabs/hardhat-zksync-solc");

module.exports = {
  zksolc: {
    version: "0.1.0",
    compilerSource: "docker",
    settings: {
      optimizer: {
        enabled: true,
      },
      experimental: {
        dockerImage: "matterlabs/zksolc",
      },
    },
  },
  zkSyncDeploy: {
    zkSyncNetwork: "https://zksync2-testnet.zksync.dev",
    ethNetwork: "goerli",
  },
  networks: {
    // To compile with zksolc, this must be the default network.
    hardhat: {
      zksync: true,
    },
  },
  solidity: {
    version: "0.8.12",
  },
};
```

Thank you :D

**Comment by ly0va** [comment]
Thank you for the report, will investigate!

**Comment by ly0va** [comment]
Sorry @jovijovi but this seems like a bug in the `solc` compiler. If you try to compile using a vanilla `solc v0.8.15` using these settings:
```
  solidity: {
    version: "0.8.15",
    settings: {
      outputSelection: {
        "*": { "*": ["irOptimized"] }
      }
    }
  },
```
you will face this error. And unfortunately, these are the settings `zksolc` uses to get the intermediate representation (yul) code for further processing.

We are working closely with the `solc` team and will try to resolve this as soon as possible.

**Comment by jovijovi** [comment]
After upgrading deps and zksolc, contracts can be compiled and deployed correctly.
I'll do more testing and close this issue in due course.
Thank you :D

- Package deps:

```json
  "dependencies": {
    "@matterlabs/hardhat-zksync-deploy": "^0.3.6",
    "@matterlabs/hardhat-zksync-solc": "^0.3.6",
    "erc721a": "4.2.2",
    "zksync-web3": "^0.7.13"
  }
```

- hardhat.config.ts

```typescript
require("@matterlabs/hardhat-zksync-deploy");
require("@matterlabs/hardhat-zksync-solc");

module.exports = {
  zksolc: {
    version: "1.1.5",
    compilerSource: "docker",
    settings: {
      optimizer: {
        enabled: true,
      },
      experimental: {
        dockerImage: "matterlabs/zksolc",
      },
    },
  },
  zkSyncDeploy: {
    zkSyncNetwork: "https://zksync2-testnet.zksync.dev",
    ethNetwork: "goerli",
  },
  networks: {
    // To compile with zksolc, this must be the default network.
    hardhat: {
      zksync: true,
    },
  },
  solidity: {
    version: "0.8.12",
  },
};
```

**Comment by ly0va** [comment]
Hey @jovijovi, I assume the issue is fixed.

Feel free to reopen if the problem still persists.
